### ISSUE TITLE
Changel `Table.name` to `Table.columnName`, `Table.name` conflicts with `Neutral.name`

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-core#167]
See https://travis-ci.org/BhallaLab/moose-core/jobs/189070633 

````
Traceback (most recent call last):

  File "/home/travis/build/BhallaLab/moose-core/tests/python/test_neuroml.py", line 42, in <module>

    test_all()

  File "/home/travis/build/BhallaLab/moose-core/tests/python/test_neuroml.py", line 25, in test_all

    test_ca1()

  File "/home/travis/build/BhallaLab/moose-core/tests/python/test_neuroml.py", line 30, in test_ca1

    loadModel(p)

  File "/home/travis/build/BhallaLab/moose-core/tests/python/neuroml/FvsI_CA1.py", line 33, in loadModel

    neuromlR.readNeuroMLFromFile(filename)

  File "/home/travis/build/BhallaLab/moose-core/_GSL_BUILD/python/moose/neuroml/NeuroML.py", line 138, in readNeuroMLFromFile

    cellDict = mmlR.readMorphML(cell,params=params,lengthUnits=self.lengthUnits)

  File "/home/travis/build/BhallaLab/moose-core/_GSL_BUILD/python/moose/neuroml/MorphML.py", line 431, in readMorphML

    'Gbar', Gfactor*gmaxval, self.bio, mechanismname)

  File "/home/travis/build/BhallaLab/moose-core/_GSL_BUILD/python/moose/neuroml/MorphML.py", line 558, in set_group_compartment_param

    self.set_compartment_param(compartment,name,value,mechanismname)

  File "/home/travis/build/BhallaLab/moose-core/_GSL_BUILD/python/moose/neuroml/MorphML.py", line 635, in set_compartment_param

    neutralObj = moose.Neutral(compartment.path+'/'+mechanismname)

TypeError: cannot convert HHChannel to moose.Neutral. To get the existing object use `moose.element(obj)` instead.

````

**Comment by dilawar** [comment]
Commit removed `name` field from `moose.Table`. It was overshadowing `Neutral::name` field.  
https://github.com/BhallaLab/moose-core/commit/9b175c858d8fe28dfebfb9d129a5719e3a05f679
