### ISSUE TITLE
Python 3.10 drops parser module

### ISSUE THREAD

**Issue by sanjayankur31** [BhallaLab/moose-core#437]
Just a note: Python 3.10 no longer includes the `parser` module:
https://bugs.python.org/issue40939

It's used in `python/moose/utils.py`.

I'm not yet sure what is to be done here, what replaces it, so I'm only filing this as an FYI. I'll try to open a PR when I learn what needs to be done.

Here's the downstream NeuroFedora bug for reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1899115

**Comment by dilawar** [comment]
I think the parser module was replaced by `ast`. It should be a quick fix. I'll wait till my other pending PRs get merged. Total blackout on those PRs. 👎🏽.

**Comment by dilawar** [comment]
You can safely detect the function which uses parser module. It is not used anywhere. The new release will get rid of this function and import.

**Comment by opoplawski** [comment]
Just removing tweak_field (and thus the parser import) is not sufficient:
```
 5/13 Test  #5: test_neuroml .....................***Failed    0.61 sec
/home/orion/fedora/moose/moose-core-3.1.5/redhat-linux-build/python/moose/utils.py:99: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(token) is 0:
Traceback (most recent call last):
  File "/home/orion/fedora/moose/moose-core-3.1.5/tests/python/test_neuroml.py", line 21, in <module>
    from neuroml.FvsI_CA1 import ca1_main, loadModel
  File "/home/orion/fedora/moose/moose-core-3.1.5/tests/python/neuroml/FvsI_CA1.py", line 22, in <module>
    from moose.neuroml.NeuroML import NeuroML
  File "/home/orion/fedora/moose/moose-core-3.1.5/redhat-linux-build/python/moose/neuroml/__init__.py", line 1, in <module>
    from .NeuroML import NeuroML, loadNeuroML_L123
  File "/home/orion/fedora/moose/moose-core-3.1.5/redhat-linux-build/python/moose/neuroml/NeuroML.py", line 48, in <module>
    from moose.utils import *
  File "/home/orion/fedora/moose/moose-core-3.1.5/redhat-linux-build/python/moose/utils.py", line 18, in <module>
    import symbol
ModuleNotFoundError: No module named 'symbol'
```
However, just removing the symbol import seems to work for that.
