### ISSUE TITLE
Bug in online documentation when using WSL

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose-core#439]
Not sure if this bug was always present or if it creeped in over the updates in the past few years:

```
Python 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import moose
>>> moose.doc('PulseGen')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/subha/.local/lib/python3.8/site-packages/moose/moose.py", line 504, in doc
    text += getmoosedoc(tokens, inherited=inherited)
  File "/home/subha/.local/lib/python3.8/site-packages/moose/moose.py", line 409, in getmoosedoc
    class_element = _moose.element('/classes/%s' % (tokens[0]))
NameError: name '_moose' is not defined
>>> help(moose.PulseGen)
Segmentation fault (core dumped)
```
The error when using `moose.doc` has an easy fix. In relation to that, it may be good to review the imports within moose.

**Comment by subhacom** [comment]
This does not appear in the nightly builds. So possibly an obsolete issue.
